# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-04-10T10:17:14+00:00

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, TypedDict, Union

from typing_extensions import NotRequired, TypeAlias

AdjustType: TypeAlias = Literal[
    "before", "after", "normal"
]


class CompactKlineData(TypedDict):
    amount: List[float]
    close: List[float]
    high: List[float]
    low: List[float]
    open: List[float]
    open_interest: NotRequired[List[float]]
    prev_close: NotRequired[List[float]]
    settlement_price: NotRequired[List[float]]
    timestamp: List[int]
    volume: List[int]


class ExFactorEntry(TypedDict):
    ex_factor: float
    timestamp: int


class Kline(TypedDict):
    amount: NotRequired[float]
    close: float
    high: float
    low: float
    open: float
    open_interest: NotRequired[Optional[float]]
    prev_close: NotRequired[Optional[float]]
    settlement_price: NotRequired[Optional[float]]
    timestamp: int
    volume: int


class QuotesQuery(TypedDict):
    symbols: NotRequired[Optional[str]]
    universes: NotRequired[Optional[str]]


class QuotesRequest(TypedDict):
    symbols: NotRequired[List[str]]
    universes: NotRequired[List[str]]


Region: TypeAlias = Literal["CN", "US", "HK"]


SessionStatus: TypeAlias = Literal[
    "pre_market", "regular", "after_hours", "closed", "halted", "lunch_break"
]


class Universe(TypedDict):
    category: str
    description: NotRequired[Optional[str]]
    id: str
    name: str
    region: str
    symbols: List[str]


class UniverseBatchRequest(TypedDict):
    ids: List[str]


class UniverseSummary(TypedDict):
    category: str
    description: NotRequired[Optional[str]]
    id: str
    name: str
    region: str
    symbol_count: int


class UniverseListResponse(TypedDict):
    data: List[UniverseSummary]
